services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db
    platform: linux/amd64
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "14330:1433"
    volumes:
      - quantapp-mssql-data:/var/opt/mssql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  backend:
    image: barneytodd27/quantapp-backend:latest
    container_name: backend
    ports:
      - "8001:8000"
    env_file:
      - ./backend/.env
    environment:
      - DB_ENGINE=mssql
      - APP_ENV=docker
    volumes:
      - ./init-db.sql:/init-db.sql
    depends_on:
      - db

  frontend:
    image: barneytodd27/quantapp-frontend:latest
    container_name: frontend
    platform: linux/amd64
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    environment:
      - REACT_APP_BACKEND_PORT=8001
    depends_on:
      - backend

volumes:
  quantapp-mssql-data:
